### ISSUE TITLE
template name needs a prefix

### ISSUE THREAD

**Issue by elijahiuu** [majgis/ngify#20]
template names are not name-spaced, they need to have some path prefixed.
```
angular.module('ngify').run(['$templateCache', function($templateCache){$templateCache.put('test.html','<table>...
```

gulp-angular-templatecache, for example, uses a full path as prefix:
```
angular.module("templates", []).run(["$templateCache", function($templateCache) {$templateCache.put("testComponent/templates/test.html"
```

**Comment by majgis** [comment]
I've been creating uniquely named files since it eliminates the refactoring step and reduces the friction of moving files around, but I'm happy to add an option to namespace the files.

You said full path, but it looks like you mean relative to the module.  I will start at the module folder and go down from there.

**Comment by elijahwww** [comment]
Hi. I just reread what you had said about prefix. I was thinking more of namespace/absolute/generated id for the following reason. App code could have structures like this (mine does):
```
/src
  ./componentA/directives
             ./templates
  ./componentB/directives
```

Directives would all do require('../templates/notUniverasallyUnique.html') and again template name collisions could occur. How does the idea of appending a gereated id sound. id1_nameCollision.html, id2_nameCollision.html, id3_realTemplate.html

**Comment by majgis** [comment]
Generating an id seems more complex and less intuitive.  You wouldn't know the ids until you bundle the file, which is awkward for making reference to in your directive for quickly setting up.  I'd rather assign my own id ( a naming convention that guarantees unique names, and immediately use it).

I do like having a module relative path because it is intuitive and it would be unique across packages as well.  We could also add an option to strip part of the path away if you aren't worried about cross package conflicts.

`htmlPath: true` outputs:
```
moduleName/src/componentA/directives/templates/template.html
```

`htmlPath: 'moduleName/src/'` outputs:
```
componentA/directives/templates/template.html 
```

`htmlPath: ['moduleName/src/', 'directives/templates/']` outputs:
```
componentA/template.html
```

This approach would give the developer full control.  It is intuitive in that you get the package relative path by default which is guaranteed to be unique.  The developer can then decide to strip redundant sections from the path as they see fit.  It is also simple to implement.

Sound ok?

**Comment by elijahwww** [comment]
It does !!! That is a better approach.

**Comment by elijahwww** [comment]
Does `require('template.html')` return anything? Do I need to call require separately from `templateUrl:` ?

```
require('./test3.html'); // this puts it in the cache
app.directive('test1', function (){
	return {
		templateUrl: 'test3.html', // this retrieves it from the cache
}});
```
it was hoping generated module would return either a string or a way to obtain it on a single line. Or am I missing something obvious?
```
app.directive('test1', function (){
	return {
		templateUrl: require('./test3.html') // this returns a string 'test3.html'
}});
```
the part about prefixes still applies :)

**Comment by elijahwww** [comment]
Oh, I might be off on my Angular understanding. Doing a require() and subsequent angular.run() maybe too late on the bootstrap sequence if that step was executed only then. :/

**Comment by majgis** [comment]
I'm using require-globify to bulk load all the files in the application, which registers test3.html in $templateCache.  

You can also just do the following to get it to work:
```
require('./test3.html');
app.directive('test1', function (){
    return {
        templateUrl: 'test3.html' 
}});
```

I will create a separate issue for requiring an html file to return the value registered with $templateCache.

**Comment by majgis** [comment]
See #23 

You might be right about it being too late in the bootstrap sequence to work, but I'll still investigate...

**Comment by Madd0g** [comment]
Just to be safe, that `htmlPath` feature doesn't exist yet, right?

**Comment by majgis** [comment]
You are correct.  I will take a look at this issue over the weekend.

**Comment by majgis** [comment]
I didn't get to this last weekend, but I haven't forgotten about it...

**Comment by chatii2412** [comment]
+1

**Comment by majgis** [comment]
Sad how long it took me, but finally done.  I'll encourage PR's from now on.
